POST http://localhost:5000/users/signup HTTP/1.1
Content-Type: application/json

{
    "username":"michael",
    "email":"joh@maghfw2444.com",
    "password":"231234",
    "comfirmpassword":"231234"

}